spring.application.name=Backend

#spring.data.mongodb.host=localhost
#spring.data.mongodb.port=27017
#spring.data.mongodb.database=cloudshare_db
spring.data.mongodb.uri=${MONGODB_URL}


spring.data.mongodb.auto-index-creation=true

server.servlet.context-path=/api
server.port=${PORT:8080}
clerk.issuer=https://flowing-boa-85.clerk.accounts.dev
clerk.jwks-url=https://flowing-boa-85.clerk.accounts.dev/.well-known/jwks.json
clerk.webhook.secret=${CLERK_WEBHOOK_SECRET}

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=25MB


razorpay.key.id=${RAZORPAY_KEY_ID}
razorpay.key.secret=${RAZORPAY_KEY_SECRET}
cloudinary.cloud_name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api_key=${CLOUDINARY_API_KEY}
cloudinary.api_secret=${CLOUDINARY_API_SECRET}